
- name: Create Volume for DB
  connection: local
  hosts: local
  gather_facts: false
  vars_files:
    - vars/vars.yml

  tasks:
   - name: Create Cinder Volume and Save ID to volume.txt 
     shell:  cinder create --display_name="{{ volume_name }}" {{ volume_size }}  
     
   - name: Display VOlume
     shell: cinder list | grep database | awk '{ print $2 }'  
     register: shell_output2
   - debug: msg="{{ shell_output2.stdout }}" 
   - local_action: copy content="{{ shell_output2.stdout }}" dest=/home/ubuntu/03-Ansible/output/volume.txt
   
